/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    404: typeof import('./src/views/error-page/404.vue')['default']
    AddCategory: typeof import('./src/components/UploadImage/AddCategory.vue')['default']
    AddOrEdit: typeof import('./src/views/usedCar/carInfo/components/AddOrEdit.vue')['default']
    App: typeof import('./src/App.vue')['default']
    AppMain: typeof import('./src/layout/components/AppMain.vue')['default']
    Brand: typeof import('./src/views/components/Brand.vue')['default']
    Breadcrumb: typeof import('./src/components/Breadcrumb/index.vue')['default']
    CarInfo: typeof import('./src/views/usedCar/carInfo/index.vue')['default']
    Communication: typeof import('./src/views/usedCar/communication/index.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ErrorPageLayout: typeof import('./src/views/error-page/components/ErrorPageLayout.vue')['default']
    FromatDate: typeof import('./src/views/components/FromatDate.vue')['default']
    Hamburger: typeof import('./src/components/Hamburger/index.vue')['default']
    Home: typeof import('./src/views/home/index.vue')['default']
    Image: typeof import('./src/components/Image/index.vue')['default']
    ImagePreview: typeof import('./src/views/components/ImagePreview.vue')['default']
    Layout: typeof import('./src/layout/index.vue')['default']
    LineandBar: typeof import('./src/components/Charts/LineandBar.vue')['default']
    Login: typeof import('./src/views/login/index.vue')['default']
    Logo: typeof import('./src/layout/components/Sidebar/Logo.vue')['default']
    Navbar: typeof import('./src/layout/components/Navbar.vue')['default']
    Pie: typeof import('./src/components/Charts/Pie.vue')['default']
    PiturePreview: typeof import('./src/components/PiturePreview/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SaleCar: typeof import('./src/views/usedCar/saleCar/index.vue')['default']
    Sidebar: typeof import('./src/layout/components/Sidebar/index.vue')['default']
    SidebarItem: typeof import('./src/layout/components/Sidebar/SidebarItem.vue')['default']
    SidebarItemLink: typeof import('./src/layout/components/Sidebar/SidebarItemLink.vue')['default']
    SvgIcon: typeof import('./src/components/SvgIcon/index.vue')['default']
    Tags: typeof import('./src/views/components/Tags.vue')['default']
    UploadImage: typeof import('./src/components/UploadImage/index.vue')['default']
  }
}
